### ISSUE TITLE
H6141 rope light is not registered correctly

### ISSUE THREAD

**Issue by wez** [wez/govee2mqtt#15]
Hi Just installed this, getting this in the logs:

[2024-01-06T21:46:23 INFO  govee::commands::serve] requesting update via IoT MQTT Sophie House Light (E1:DA:A4:C1:38:61:B0:9E) None
and device has a RED ! status in MQTT --> Entities

![image](https://github.com/wez/govee2mqtt/assets/57002638/0008a8da-9d3d-483e-a817-28e4ac822d63)

Any ideas what I've done wrong? Logs look fine otherwise.

Logs from HASS:

Exception in functools.partial(<function _async_discover at 0x7f708e98a0>, <HomeAssistant RUNNING>, 'light', <function async_setup_entity_entry_helper.<locals>.async_setup_from_discovery at 0x7f6c2e1e40>, None) when dispatching 'mqtt_discovery_new_light_mqtt': ({'availability_topic': 'gv2mqtt/availability', 'name': None, 'origin': {'name': 'gv2mqtt', 'sw_version': '2024.01.06-0da21047', 'support_url': 'https://github.com/wez/govee2mqtt'}, 'device': {'name': 'Sophie House Light', 'manufacturer': 'Govee', 'model': 'H6141', 'via_device': 'gv2mqtt', 'identifiers': ['gv2mqtt-E1DAA4C13861B09E']}, 'unique_id': 'gv2mqtt-E1DAA4C13861B09E', 'schema': 'json', 'command_topic': 'gv2mqtt/light/E1DAA4C13861B09E/command', 'state_topic': 'gv2mqtt/light/E1DAA4C13861B09E/state', 'supported_color_modes': [], 'color_mode': False, 'brightness': False, 'brightness_scale': 100, 'effect': True, 'effect_list': ['Active', 'Afternoon', 'Aurora', 'Breathe', 'Business', 'Candlelight', 'Canyon', 'Care', 'Christmas', 'Clear lake', 'Cornfield', 'Crazy', 'Dance Party', 'Dating', 'Desert', 'Disco', 'Downpour', 'Dreamland', 'Dusk', 'Energetic', 'Enthusiastic', 'Excited', 'Fall', 'Fantasy', "Father's Day", 'Fight', 'Fire', 'Flash', 'Flower Field', 'Forest', 'Game', 'Ghost', 'Glacier', 'Grassland', 'Halloween', 'Happy', 'Heartbeat', 'Karst Cave', 'Leisure', 'Leisure-A', 'Leisure-B', 'Lightning', 'Longing', 'Meditation', 'Moonlight', 'Morning', "Mother's Day", 'Movie', 'Night', 'Night Light', 'Party', 'Profound', 'Quiet', 'Rainbow', 'Reading', 'Relax', 'Retro', 'River', 'Romantic', 'Siren', 'Sky', 'Sleep', 'Solar flare', 'Solar Halo', 'Sports', 'Spring', 'Star', 'Starry Sky', 'Study', 'Summer', 'Sunrise', 'Sunset', 'Sunset Glow', 'Sweet', 'Tension', 'test govee diy', 'Thanksgiving', 'Twinkle', 'Universe', "Valentine's Day", 'Warm', 'Wave', 'Winter', 'Work'], 'min_mireds': None, 'max_mireds': None, 'payload_available': 'online', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 356, in _async_discover setup(discovery_payload) File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 417, in async_setup_from_discovery config: DiscoveryInfoType = discovery_schema(discovery_payload) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 232, in __call__ return self._exec((Schema(val) for val in self.validators), v) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 351, in _exec v = func(v) ^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable return schema(data) ^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 40, in validate_mqtt_light_discovery config: ConfigType = schemas[config_value[CONF_SCHEMA]](config_value) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 232, in __call__ return self._exec((Schema(val) for val in self.validators), v) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 351, in _exec v = func(v) ^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable return schema(data) ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict return base_validate(path, iteritems(data), out) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 387, in validate_mapping cval = cvalue(key_path, value) ^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 229, in _run return self._exec(self._compiled, value, path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 353, in _exec v = func(path, v) ^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable return schema(data) ^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 155, in valid_supported_color_modes raise vol.Error(f"Invalid supported_color_modes {sorted(color_modes)}") voluptuous.error.Error: Invalid supported_color_modes []

_Originally posted by @cm-mojo in https://github.com/wez/govee2mqtt/issues/14#issuecomment-1879843021_

**Comment by wez** [comment]
It seems like those devices aren't actually lights? Assuming that is the case, here's what I suggest:

1. Delete the device by finding it in the mqtt section and pressing delete:

![image](https://github.com/wez/govee2mqtt/assets/117777/565d8580-f068-4ec3-8c16-11d2808688bf)

2. Go to the addons section and check for updates.  Update the addon to the latest version (`2024.01.06-bb8fdbb3`) which will avoid registering the light entity if it doesn't seem like the device is controllable as a light.  You should still have a power switch entity though.

**Comment by cm-mojo** [comment]
They are rgb rope lights

**Comment by wez** [comment]
Can you update the addon and share the logs from the addon?  It should show the metadata returned from Govee for your various devices.
I suspect that this device, like the Glide lights, has bogus data being returned from the API.

**Comment by cm-mojo** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=core-mosquitto
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_MQTT_USER=addons
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-01-06T23:30:41 INFO  govee::commands::serve] Starting service. version 2024.01.06-bb8fdbb3
[2024-01-06T23:30:41 INFO  govee::commands::serve] Querying platform API for device list
[2024-01-06T23:30:41 INFO  govee::commands::serve] Querying undocumented API for device + room list
[2024-01-06T23:30:43 INFO  govee::service::iot] Connected to IoT: CONNACK code 0: Connection Accepted.
[2024-01-06T23:30:43 INFO  govee::commands::serve] Devices returned from Govee's APIs
[2024-01-06T23:30:43 INFO  govee::commands::serve] Sophie House Light (E1:DA:A4:C1:38:61:B0:9E) sku=H6141
[2024-01-06T23:30:43 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=false supports_brightness=false
[2024-01-06T23:30:43 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-01-06T23:30:43 INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=false
[2024-01-06T23:30:43 INFO  govee::commands::serve] 
[2024-01-06T23:30:43 INFO  govee::commands::serve] House light 2 (2C:60:A4:C1:38:D7:36:34) sku=H6141
[2024-01-06T23:30:43 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=false supports_brightness=false
[2024-01-06T23:30:43 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-01-06T23:30:43 INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=true
[2024-01-06T23:30:43 INFO  govee::commands::serve] 
[2024-01-06T23:30:43 INFO  govee::commands::serve] Starting LAN discovery
[2024-01-06T23:30:43 INFO  govee::service::iot] IoT (re)connected with status CONNACK code 0: Connection Accepted.
[2024-01-06T23:30:44 INFO  govee::service::http] http server addr is 0.0.0.0:8056

**Comment by wez** [comment]
I've added a quirk for this device, so if you check for updates in the addons section and update, hopefully you'll be able to control those devices!

**Comment by cm-mojo** [comment]
Hi, I van turn it on and off, but no brightness or colour control, so step
in the right direction!

**Comment by wez** [comment]
Anything in the logs? 
If not, try setting the debug level to `govee::lan_api=trace,info` and share what you see when you try to control the device.

**Comment by cm-mojo** [comment]
2024-01-07T08:21:56 INFO  govee::service::hass] Command for Sophie
House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"ON","color_temp":500}
[2024-01-07T08:21:56 ERROR govee::service::hass] While dispatching
Message { topic: "gv2mqtt/light/E1DAA4C13861B09E/command", payload:
"{\"state\":\"ON\",\"color_temp\":500}", qos: AtMostOnce, retain:
false, mid: 0 }: device has no colorTemperatureK
[2024-01-07T08:22:02 INFO  govee::service::hass] Command for Sophie
House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"ON"}
[2024-01-07T08:22:03 INFO  govee::service::hass] Command for Sophie
House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"OFF"}
[2024-01-07T08:22:05 INFO  govee::service::hass] Command for Sophie
House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"ON"}
[2024-01-07T08:22:09 INFO  govee::service::hass] Command for Sophie
House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"ON"}
[2024-01-07T08:22:16 INFO  govee::service::hass] Command for Sophie
House Light (E1:DA:A4:C1:38:61:B0:9E):
{"state":"ON","color":{"r":255,"g":158,"b":243}}
[2024-01-07T08:22:16 ERROR govee::service::hass] While dispatching
Message { topic: "gv2mqtt/light/E1DAA4C13861B09E/command", payload:
"{\"state\":\"ON\",\"color\":{\"r\":255,\"g\":158,\"b\":243}}", qos:
AtMostOnce, retain: false, mid: 0 }: device has no colorRgb
[2024-01-07T08:22:17 INFO  govee::service::hass] Command for Sophie
House Light (E1:DA:A4:C1:38:61:B0:9E):
{"state":"ON","color":{"r":255,"g":158,"b":243}}
[2024-01-07T08:22:17 ERROR govee::service::hass] While dispatching
Message { topic: "gv2mqtt/light/E1DAA4C13861B09E/command", payload:
"{\"state\":\"ON\",\"color\":{\"r\":255,\"g\":158,\"b\":243}}", qos:
AtMostOnce, retain: false, mid: 0 }: device has no colorRgb
[2024-01-07T08:22:17 INFO  govee::service::hass] Command for Sophie
House Light (E1:DA:A4:C1:38:61:B0:9E):
{"state":"ON","color":{"r":255,"g":158,"b":243}}
[2024-01-07T08:22:17 ERROR govee::service::hass] While dispatching
Message { topic: "gv2mqtt/light/E1DAA4C13861B09E/command", payload:
"{\"state\":\"ON\",\"color\":{\"r\":255,\"g\":158,\"b\":243}}", qos:
AtMostOnce, retain: false, mid: 0 }: device has no colorRgb

**Comment by wez** [comment]
OK, I think the issue here is:
* The Platform API doesn't work for this device
* We try to fall back to the LAN API
* LAN API is not supported for this device
* We try the platform API anyway, which doesn't work

To solve this, I think I'll need to add another control strategy for this device, will need to think on it.

**Comment by wez** [comment]
Please update the addon and let me know how things work out; I added a fallback to the undocumented IoT mqtt interface for this case.

**Comment by cm-mojo** [comment]
Finds it but no control available at all - controls are greyed out in HA.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=core-mosquitto
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_MQTT_USER=addons
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-01-07T18:16:18 INFO  govee::commands::serve] Starting service. version 2024.01.07-92fb55e0
[2024-01-07T18:16:18 INFO  govee::commands::serve] Querying platform API for device list
[2024-01-07T18:16:18 INFO  govee::commands::serve] Querying undocumented API for device + room list
[2024-01-07T18:16:19 INFO  govee::service::iot] Connected to IoT: CONNACK code 0: Connection Accepted.
[2024-01-07T18:16:19 INFO  govee::commands::serve] Starting LAN discovery
[2024-01-07T18:16:19 INFO  govee::service::iot] IoT (re)connected with status CONNACK code 0: Connection Accepted.
[2024-01-07T18:16:23 INFO  govee::commands::serve] Devices returned from Govee's APIs
[2024-01-07T18:16:23 INFO  govee::commands::serve] Sophie House Light (E1:DA:A4:C1:38:61:B0:9E) sku=H6141
[2024-01-07T18:16:23 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=false supports_brightness=false
[2024-01-07T18:16:23 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-01-07T18:16:23 INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=false
[2024-01-07T18:16:23 INFO  govee::commands::serve]   Quirk: Quirk { sku: "H6141", icon: "mdi:led-strip-variant", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: true, ble_only: false, lan_api_capable: false }
[2024-01-07T18:16:23 INFO  govee::commands::serve] 
[2024-01-07T18:16:23 INFO  govee::commands::serve] Noah House (2C:60:A4:C1:38:D7:36:34) sku=H6141
[2024-01-07T18:16:23 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=false supports_brightness=false
[2024-01-07T18:16:23 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-01-07T18:16:23 INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=true
[2024-01-07T18:16:23 INFO  govee::commands::serve]   Quirk: Quirk { sku: "H6141", icon: "mdi:led-strip-variant", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: true, ble_only: false, lan_api_capable: false }
[2024-01-07T18:16:23 INFO  govee::commands::serve] 
[2024-01-07T18:16:23 INFO  govee::service::http] http server addr is 0.0.0.0:8056
[2024-01-07T18:16:28 INFO  govee::service::hass] MQTT connected with status=CONNACK code 0: Connection Accepted.
[2024-01-07T18:16:43 INFO  govee::commands::serve] requesting update via IoT MQTT Sophie House Light (E1:DA:A4:C1:38:61:B0:9E) None
[2024-01-07T18:16:43 INFO  govee::commands::serve] requesting update via IoT MQTT Noah House (2C:60:A4:C1:38:D7:36:34) None
[2024-01-07T18:18:17 INFO  govee::service::hass] Command for Sophie House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"OFF"}
[2024-01-07T18:18:21 INFO  govee::service::hass] powerSwitch for E1DAA4C13861B09E: OFF
[2024-01-07T18:18:24 INFO  govee::service::hass] powerSwitch for E1DAA4C13861B09E: OFF
[2024-01-07T18:18:35 INFO  govee::service::hass] powerSwitch for E1DAA4C13861B09E: OFF
[2024-01-07T18:18:39 INFO  govee::service::hass] Command for Sophie House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"OFF"}
[2024-01-07T18:18:50 INFO  govee::service::hass] Command for Sophie House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"OFF"}
[2024-01-07T18:18:53 INFO  govee::service::hass] Command for Sophie House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"ON","color":{"r":255,"g":110,"b":84}}
[2024-01-07T18:18:54 INFO  govee::service::hass] Command for Sophie House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"ON","color_temp":500}
[2024-01-07T18:18:55 INFO  govee::service::hass] Command for Sophie House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"ON","color":{"r":127,"g":172,"b":255}}
[2024-01-07T18:18:55 INFO  govee::service::hass] Command for Sophie House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"OFF"}
[2024-01-07T18:18:56 INFO  govee::service::hass] Command for Sophie House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"ON","color":{"r":127,"g":172,"b":255}}
[2024-01-07T18:18:56 INFO  govee::service::hass] Command for Sophie House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"ON","color":{"r":127,"g":172,"b":255}}
[2024-01-07T18:18:57 INFO  govee::service::hass] Command for Sophie House Light (E1:DA:A4:C1:38:61:B0:9E): {"state":"ON"}
[2024-01-07T18:19:57 INFO  govee::service::hass] Home Assistant status changed: offline
[2024-01-07T18:21:26 INFO  govee::service::hass] Home Assistant status changed: online

**Comment by wez** [comment]
The logs you shared suggest that the device does show up in hass and that hass is sending commands to it. That doesn't match up with what you said about it being greyed out and not controllable.

Can you clarify what you're seeing?

**Comment by cm-mojo** [comment]
See attached, cpntrols are greyed out. I cannot press them

**Comment by wez** [comment]
There's no attachment.

Your logs show that something in hass did attempt to control the device. I'm trying to understand why that doesn't match up to what you described.

Try forcing a refresh in the hass UI, or restarting the hass mobile app?

**Comment by cm-mojo** [comment]
I've rebooted the pi it's on, and still no control over the device.

**Comment by wez** [comment]
At this point I don't know what I can do here. What you described about what shows up in hass doesn't match the logs you shared and you're not sharing the information I asked for.

Please make another pass at carefully documenting what you're seeing and trying and the logs from the addon and anything relevant from the home assistant logs and re-open this once you've collected that information, and we can go from there.

**Comment by cm-mojo** [comment]
Hello chap, apologies as you can imagine this is a hobby for me too, so sorry not been able to followup. I've tried to reattach the images that were missing above. I agree it seems like HASS is communicating, what I'm seeing though is that although the devices look like they are setup and should be actionable, when I click on the buttons in the interface, nothing happens. They don't change state, and as far as I can see nothing happens in the logs at that point.  I can see in the logs that there is no entry that corresponds to me trying to switch the device on and off at the times I tried it.

From a next steps perspective, if you tell me exactly what you want me to try, I can do it and report back. 

Perhaps best bet would be if I clear the log, then click the power on button in the interface then report back logs from both the addon and the hass mqtt broker log that would give you a view?


![Screenshot_20240107_190906_Home Assistant](https://github.com/wez/govee2mqtt/assets/57002638/18061cfd-c5c6-43ff-ade7-60c004a41f1c)
![Screenshot_20240107_193856_Edge](https://github.com/wez/govee2mqtt/assets/57002638/23c75ead-2390-4d52-badc-7d5132fbaddd)
